// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createDiretorStmt, err = db.PrepareContext(ctx, createDiretor); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDiretor: %w", err)
	}
	if q.deleteDiretorStmt, err = db.PrepareContext(ctx, deleteDiretor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDiretor: %w", err)
	}
	if q.getDiretorByIdStmt, err = db.PrepareContext(ctx, getDiretorById); err != nil {
		return nil, fmt.Errorf("error preparing query GetDiretorById: %w", err)
	}
	if q.listDiretoresStmt, err = db.PrepareContext(ctx, listDiretores); err != nil {
		return nil, fmt.Errorf("error preparing query ListDiretores: %w", err)
	}
	if q.updateDiretorStmt, err = db.PrepareContext(ctx, updateDiretor); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDiretor: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createDiretorStmt != nil {
		if cerr := q.createDiretorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDiretorStmt: %w", cerr)
		}
	}
	if q.deleteDiretorStmt != nil {
		if cerr := q.deleteDiretorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDiretorStmt: %w", cerr)
		}
	}
	if q.getDiretorByIdStmt != nil {
		if cerr := q.getDiretorByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDiretorByIdStmt: %w", cerr)
		}
	}
	if q.listDiretoresStmt != nil {
		if cerr := q.listDiretoresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDiretoresStmt: %w", cerr)
		}
	}
	if q.updateDiretorStmt != nil {
		if cerr := q.updateDiretorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDiretorStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                 DBTX
	tx                 *sql.Tx
	createDiretorStmt  *sql.Stmt
	deleteDiretorStmt  *sql.Stmt
	getDiretorByIdStmt *sql.Stmt
	listDiretoresStmt  *sql.Stmt
	updateDiretorStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		createDiretorStmt:  q.createDiretorStmt,
		deleteDiretorStmt:  q.deleteDiretorStmt,
		getDiretorByIdStmt: q.getDiretorByIdStmt,
		listDiretoresStmt:  q.listDiretoresStmt,
		updateDiretorStmt:  q.updateDiretorStmt,
	}
}
